baseURL = 'https://caleb-brown.dev/'
languageCode = 'en-us'
title = 'Caleb Brown'
theme = "hugo-coder"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Caleb Brown"
  info = "Game Developer | Software Engineer"
  description = "Caleb Brown's personal website"
  keywords = "developer,personal"
  avatarurl = "images/profile_Cropped.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "images/logos/favicon-32x32.png"
  favicon_16 = "images/logos/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

#   customCSS = ["css/custom.css"]
#   customSCSS = ["scss/custom.scss"]
#   customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/caleb-brown/"
[[params.social]]
  name = "Gitea"
  icon = "fa fa-gitea fa-2x"
  weight = 2
  url = "https://git.caleb-brown.dev/caleb-brown/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/dev_caleb/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 4
  url = "https://linkedin.com/in/calebmatthewbrown"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url = "projects/"
[[menu.main]]
  name = "Contact"
  weight = 3
  url = "contact/"